openapi: 3.0.1
info:
  title: Contracts Service API
  version: 0.1.0
paths:
  /api/v1/contracts/sign:
    post:
      summary: Sign contract
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: signed
